mkdir -pv .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxcomp .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxconsole .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxmerger .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxrender .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxvr .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/slg4 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/pylux.so .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/liblux.so .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxcoreconsole .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxcoredemo .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxcoreimplserializationdemo .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxcorescenedemo .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/luxcoreui .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/bin/benchsimple .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/pyluxcore.so .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libpython3.so .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libpython3.5m.so.1.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libOpenImageIO.so.1.6.3 ./libOpenImageIO.so.1.6
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_thread.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_program_options.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_filesystem.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_serialization.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_iostreams.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_regex.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_system.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_chrono.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_date_time.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_atomic.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_python3.so.1.56.0 .
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libboost_python3.so.1.56.0 ./libboost_python.so.1.56.0
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libIlmImf-2_2.so.22.0.0 ./libIlmImf-2_2.so.22
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libHalf.so.12.0.0 ./libHalf.so.12
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libIex-2_2.so.12.0.0 ./libIex-2_2.so.12
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libIlmThread-2_2.so.12.0.0 ./libIlmThread-2_2.so.12
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libembree.so.2.17.7 ./libembree.so.2
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libtbb.so ./libtbb.so
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libtbbmalloc.so ./libtbbmalloc.so
cp ~/.local/share/flatpak/app/org.luxrender.luxrender17/current/active/files/lib/libGLU.so.1.3.1 ./libGLU.so.1