cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/bin/luxcomp ./
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/bin/luxconsole ./
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/bin/luxmerger ./
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/bin/luxrender ./
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/bin/pylux.so ./
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/bin/liblux.so ./
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libpython3.so ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libpython3.5m.so.1.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libglut.so.3.11.1 ./lib/libglut.so.3
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_thread.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_program_options.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_filesystem.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_serialization.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_iostreams.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_regex.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_system.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_chrono.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_date_time.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_atomic.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_python3.so.1.56.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libboost_python3.so.1.56.0 ./lib/libboost_python.so.1.56.0
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libOpenImageIO_Util.so.1.6.3 ./lib/libOpenImageIO_Util.so.1.6
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libOpenImageIO.so.1.6.3 ./lib/libOpenImageIO.so.1.6
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libImath-3_1.so.29.8.0 ./lib/libImath-3_1.so
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libIlmThread-2_2.so.12.0.0 ./lib/libIlmThread-2_2.so.12
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libIex-2_2.so.12.0.0 ./lib/libIex-2_2.so.12
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libdeflate.so.0 ./lib/
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libembree.so.2.17.7 ./lib/libembree.so.2
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libtbb.so ./lib//libtbb.so
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libtbbmalloc.so ./lib/libtbbmalloc.so
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libGLU.so.1.3.1 ./lib/libGLU.so.1
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libHalf.so.12.0.0 ./lib/libHalf.so.12
cp -v ~/.local/share/flatpak/app/org.luxrender.luxrenderui/current/active/files/lib/libIlmImf-2_2.so.22.0.0 ./lib/libIlmImf-2_2.so.22
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libtiff.so.5.8.0 ./lib/libtiff.so.5
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libjpeg.so.62.3.0 ./lib/libjpeg.so.62
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libz.so.1.3.1 ./lib/libz.so.1
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libzstd.so.1.5.5 ./lib/libzstd.so.1
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libpng16.so.16.43.0 ./lib/libpng16.so.16
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libicuuc.so.71.1 ./lib/libicuuc.so.71
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libicui18n.so.71.1 ./lib/libicui18n.so.71
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libicudata.so.71.1 ./lib/libicudata.so.71
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libgomp.so.1.0.0 ./lib/libgomp.so.1
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libfreetype.so.6.18.3 ./lib/libfreetype.so.6
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libfftw3.so.3.6.10 ./lib/libfftw3.so.3
cp -v ~/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.15-22.08/active/files/lib/x86_64-linux-gnu/libbz2.so.1.0.8 ./lib/libbz2.so.1
